//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Mining_Assignment3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data_Mining_Assignment3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4,5.8,1.2,0.2,LongEaredOwl
        ///2.8,7.4,6.1,1.9,SnowyOwl
        ///2.7,5.2,3.9,1.4,BarnOwl
        ///3.2,4.6,1.4,0.2,LongEaredOwl
        ///3.3,6.7,5.7,2.5,SnowyOwl
        ///3,4.4,1.3,0.2,LongEaredOwl
        ///2.5,6.3,4.9,1.5,BarnOwl
        ///3.3,6.7,5.7,2.1,SnowyOwl
        ///3.2,4.7,1.3,0.2,LongEaredOwl
        ///3,6.5,5.2,2,SnowyOwl
        ///3,6.1,4.6,1.4,BarnOwl
        ///3,4.8,1.4,0.3,LongEaredOwl
        ///3.9,5.4,1.7,0.4,LongEaredOwl
        ///2.8,6.3,5.1,1.5,SnowyOwl
        ///3,6.7,5,1.7,BarnOwl
        ///3.6,4.6,1,0.2,LongEaredOwl
        ///2.5,5.6,3.9,1.1,BarnOwl
        ///3.3,6.3,4.7,1.6,BarnOwl
        ///3,7.1,5.9,2.1,SnowyOwl
        ///2.5,5.5,4,1.3,Ba [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Owls {
            get {
                return ResourceManager.GetString("Owls", resourceCulture);
            }
        }
    }
}
